### ISSUE TITLE
Failed building the recipe

### ISSUE THREAD

**Issue by saberdsl** [michaelrsweet/recipes-pappl#2]
I have tried the new pappl recipe with the original cups recipe in poky layer.I got the following error:
ERROR: pappl-1.3.2-r0 do_package_qa: QA Issue: File /usr/lib/libpappl.so.1 in package pappl doesn't have GNU_HASH (didn't pass LDFLAGS?) [ldflags]
ERROR: pappl-1.3.2-r0 do_package_qa: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /home/dean/var-fsl-yocto/build_xwayland/tmp/work/armv8a-fslc-linux/pappl/1.3.2-r0/temp/log.do_package_qa.58812
ERROR: Task (/home/dean/var-fsl-yocto/sources/meta-titan/recipes-printing/pappl/pappl_1.3.2.bb:do_package_qa) failed with exit code '1'

I was trying to fix it with the solution from Yocto by adding TARGET_CC_ARCH += "${LDFLAGS}" .Unfortunately, it was still not working.

I tried your cups recipe , but got the error ERROR: Nothing RPROVIDES 'cups-lib' which was required .

**Comment by michaelrsweet** [comment]
Not sure what is going wrong here, as PAPPL's configure script will inherit all of the LDFLAGS.

Similarly, not sure what is happening with the CUPS stuff, but will try to track it down because the version Yocto serves up is ancient.

**Comment by michaelrsweet** [comment]
As this is the same as issue #1, closing this as a dupe.
